services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: tradematangi-dynamodb
    user: root
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    working_dir: /home/dynamodblocal

volumes:
  dynamodb-data:
    name: tradematangi-dynamodb-data
