import { useEffect, useState } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { ChartTile } from './ChartTile'
import type { Candle } from './contracts'

interface HistoricalPage { candles: Candle[]; available?: boolean; unavailable_reason?: string }
interface Instrument { symbol: string; display_name: string; option_eligible: boolean; supported_intervals: number[] }
interface Catalogue { instruments: Instrument[] }
interface OptionMetadata { expiries: string[]; strike_interval: number; rights: string[]; available: boolean; unavailable_reason?: string }
interface TileConfig { id: string; kind: 'spot' | 'option'; symbol: string; interval: string; tradingDate: string; expiry: string; strike: string; right: string }
interface Screen { id: string; name: string; tiles: TileConfig[] }
type Api = <T,>(path: string, params?: URLSearchParams) => Promise<T>
const fallbackCatalogue: Instrument[] = [{ symbol: 'NIFTY', display_name: 'NIFTY 50', option_eligible: true, supported_intervals: [1, 3, 5, 15, 30, 60] }]
const newTile = (): TileConfig => ({ id: crypto.randomUUID(), kind: 'spot', symbol: 'NIFTY', interval: '5', tradingDate: '2026-05-06', expiry: '', strike: '', right: 'CE' })
const newScreen = (number: number): Screen => ({ id: crypto.randomUUID(), name: `Screen ${number}`, tiles: [newTile()] })

function InstrumentPicker({ initial, catalogue, api, onSave, onClose }: { initial: TileConfig; catalogue: Instrument[]; api: Api; onSave: (tile: TileConfig) => void; onClose: () => void }) {
  const [draft, setDraft] = useState(initial)
  const [metadata, setMetadata] = useState<OptionMetadata | null>(null)
  const [openingPrice, setOpeningPrice] = useState<number | null>(null)
  const [error, setError] = useState('')
  const instrument = catalogue.find(item => item.symbol === draft.symbol) ?? fallbackCatalogue[0]
  useEffect(() => {
    if (draft.kind !== 'option') return
    let active = true
    const params = new URLSearchParams({ symbol: draft.symbol, trading_date: draft.tradingDate, interval_minutes: '1', context_days: '0' })
    void Promise.all([api<OptionMetadata>('metadata', new URLSearchParams({ symbol: draft.symbol, as_of_date: draft.tradingDate })), api<HistoricalPage>('history', params)]).then(([nextMetadata, page]) => {
      if (!active) return
      setMetadata(nextMetadata)
      const opening = page.candles.find(candle => new Date(candle.timestamp * 1000).toISOString().slice(0, 10) === draft.tradingDate)?.open ?? page.candles[0]?.open ?? null
      setOpeningPrice(opening)
      const gap = nextMetadata.strike_interval
      const defaultStrike = opening === null ? '' : String(Math.round(opening / gap) * gap)
      setDraft(current => ({ ...current, expiry: nextMetadata.expiries.includes(current.expiry) ? current.expiry : (nextMetadata.expiries[0] ?? ''), right: nextMetadata.rights.includes(current.right) ? current.right : (nextMetadata.rights[0] ?? 'CE'), strike: current.strike && Number(current.strike) % gap === 0 ? current.strike : defaultStrike }))
    }).catch(reason => active && setError(String(reason)))
    return () => { active = false }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [draft.kind, draft.symbol, draft.tradingDate])
  const gap = metadata?.strike_interval ?? 0
  const baseStrike = openingPrice === null || !gap ? 0 : Math.round(openingPrice / gap) * gap
  const strikes = baseStrike ? Array.from({ length: 21 }, (_, index) => baseStrike + (index - 10) * gap).filter(value => value > 0) : []
  return <div className="modal-backdrop" role="presentation"><section className="instrument-modal" role="dialog" aria-modal="true" aria-label="Select chart instrument"><header><strong>Select instrument</strong><button onClick={onClose}>×</button></header><div className="picker-fields"><label>Type<select value={draft.kind} onChange={event => setDraft({ ...draft, kind: event.target.value as TileConfig['kind'], expiry: '', strike: '' })}><option value="spot">Equity / index</option><option value="option" disabled={!instrument.option_eligible}>Option</option></select></label><label>Symbol<select value={draft.symbol} onChange={event => setDraft({ ...draft, symbol: event.target.value, expiry: '', strike: '' })}>{catalogue.map(item => <option key={item.symbol} value={item.symbol}>{item.display_name}</option>)}</select></label><label>Browse date<input type="date" value={draft.tradingDate} onChange={event => setDraft({ ...draft, tradingDate: event.target.value, expiry: '', strike: '' })} /></label>{draft.kind === 'option' && <><label>Expiry<select value={draft.expiry} onChange={event => setDraft({ ...draft, expiry: event.target.value })} disabled={!metadata?.available}>{metadata?.expiries.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Underlying open<input value={openingPrice ?? 'Loading…'} readOnly /></label><label>Strike<select value={draft.strike} onChange={event => setDraft({ ...draft, strike: event.target.value })} disabled={!strikes.length}>{strikes.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Right<select value={draft.right} onChange={event => setDraft({ ...draft, right: event.target.value })}>{metadata?.rights.map(value => <option key={value} value={value}>{value}</option>)}</select></label></>}</div>{metadata && !metadata.available && <p className="tile-notice">{metadata.unavailable_reason}</p>}{error && <p className="tile-notice">{error}</p>}<footer><button onClick={onClose}>Cancel</button><button className="selected" disabled={draft.kind === 'option' && (!draft.expiry || !draft.strike || !metadata?.available)} onClick={() => onSave(draft)}>Apply to chart</button></footer></section></div>
}

function DesktopTile({ config, catalogue, connection, api, onConfigure, onMaximize, onIntervalChange, maximized }: { config: TileConfig; catalogue: Instrument[]; connection: string; api: Api; onConfigure: () => void; onMaximize: () => void; onIntervalChange: (interval: string) => void; maximized: boolean }) {
  const [metadata, setMetadata] = useState<OptionMetadata | null>(null)
  const [candles, setCandles] = useState<Candle[]>([])
  const [status, setStatus] = useState('')
  const [loading, setLoading] = useState(false)
  useEffect(() => { if (config.kind === 'option' && connection === 'connected') void api<OptionMetadata>('metadata', new URLSearchParams({ symbol: config.symbol, as_of_date: config.tradingDate })).then(setMetadata).catch(error => setStatus(String(error))) }, [config.kind, config.symbol, config.tradingDate, connection])
  useEffect(() => { if (connection !== 'connected' || (config.kind === 'option' && (!config.expiry || !config.strike || !metadata?.available))) return; let active = true; setCandles([]); setStatus(''); setLoading(true); const params = new URLSearchParams({ symbol: config.symbol, trading_date: config.tradingDate, interval_minutes: config.interval, context_days: '5' }); if (config.kind === 'option') { params.set('expiry', config.expiry); params.set('strike', config.strike); params.set('right', config.right) }; void api<HistoricalPage>(config.kind === 'option' ? 'optionHistory' : 'history', params).then(page => { if (active) { setCandles(page.candles); setStatus(page.available === false ? (page.unavailable_reason ?? 'Option unavailable') : '') } }).catch(error => active && setStatus(String(error))).finally(() => active && setLoading(false)); return () => { active = false } }, [config.expiry, config.interval, config.kind, config.right, config.strike, config.symbol, config.tradingDate, connection, metadata?.available])
  const label = config.kind === 'option' ? `${config.symbol} ${config.expiry} ${config.strike} ${config.right}` : config.symbol
  return <div className={`workspace-tile ${maximized ? 'is-maximized' : ''}`}><ChartTile symbol={label} interval={`${config.interval}m`} supportedIntervals={catalogue.find(item => item.symbol === config.symbol)?.supported_intervals ?? fallbackCatalogue[0].supported_intervals} onIntervalChange={onIntervalChange} candles={candles} loading={loading} message={status} onConfigure={onConfigure} onMaximize={onMaximize} maximized={maximized} /></div>
}

export default function App() {
  const [serverUrl, setServerUrl] = useState('http://localhost:8700'), [email, setEmail] = useState('admin@tradematangi.com'), [password, setPassword] = useState('admin123'), [connection, setConnection] = useState<'connected' | 'offline' | 'authentication_required'>('authentication_required'), [loginError, setLoginError] = useState(''), [browserToken, setBrowserToken] = useState(''), [mode, setMode] = useState<'Browse' | 'Live' | 'Replay' | 'Stepwise'>('Browse'), [catalogue, setCatalogue] = useState<Instrument[]>(fallbackCatalogue), [screens, setScreens] = useState<Screen[]>([newScreen(1)])
  const [activeScreenId, setActiveScreenId] = useState(screens[0].id), [pickerTileId, setPickerTileId] = useState<string | null>(null), [maximizedTileId, setMaximizedTileId] = useState<string | null>(null)
  const hasNativeHost = '__TAURI_INTERNALS__' in window
  const api: Api = async (path, params) => { if (hasNativeHost) { const commands: Record<string, string> = { catalogue: 'desktop_catalogue', metadata: 'desktop_option_metadata', history: 'desktop_historical_page', optionHistory: 'desktop_option_historical_page' }; const values = Object.fromEntries((params ?? new URLSearchParams()).entries()); return invoke(commands[path], { baseUrl: serverUrl, ...values, intervalMinutes: Number(values.interval_minutes), strike: Number(values.strike) }) }; const route = path === 'catalogue' ? 'catalogue' : path === 'metadata' ? 'option-metadata' : path === 'history' ? 'historical/pages' : 'options/historical/pages'; const response = await fetch(`${serverUrl.replace(/\/$/, '')}/api/desktop/v1/${route}${params ? `?${params}` : ''}`, { headers: { Authorization: `Bearer ${browserToken}` } }); if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json() }
  const login = async () => { try { setLoginError(''); if (hasNativeHost) await invoke('desktop_login', { baseUrl: serverUrl, email, password }); else { const response = await fetch(`${serverUrl.replace(/\/$/, '')}/api/auth/desktop/token`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, device_name: 'Browser development preview' }) }); if (!response.ok) throw new Error('Login failed: check your email and password'); setBrowserToken((await response.json() as { access_token: string }).access_token) }; setConnection('connected') } catch (error) { setConnection('authentication_required'); setLoginError(String(error)) } }
  useEffect(() => { if (connection === 'connected') void api<Catalogue>('catalogue').then(value => setCatalogue(value.instruments)).catch(() => undefined) }, [browserToken, connection, serverUrl])
  const activeScreen = screens.find(screen => screen.id === activeScreenId) ?? screens[0], pickerTile = activeScreen.tiles.find(tile => tile.id === pickerTileId)
  const setTileCount = (count: number) => setScreens(current => current.map(screen => screen.id === activeScreenId ? { ...screen, tiles: count > screen.tiles.length ? [...screen.tiles, ...Array.from({ length: count - screen.tiles.length }, newTile)] : screen.tiles.slice(0, count) } : screen))
  const saveTile = (tile: TileConfig) => { setScreens(current => current.map(screen => screen.id === activeScreenId ? { ...screen, tiles: screen.tiles.map(item => item.id === tile.id ? tile : item) } : screen)); setPickerTileId(null) }
  const addScreen = () => { const next = newScreen(screens.length + 1); setScreens(current => [...current, next]); setActiveScreenId(next.id) }
  if (connection === 'authentication_required') return <main className="login-page"><section className="login-card"><h1>Trade Matangi Charts</h1><p>Sign in to the chart-only desktop companion.</p><label>Server URL<input value={serverUrl} onChange={event => setServerUrl(event.target.value)} /></label><label>Email<input value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>{loginError && <p className="login-error">{loginError}</p>}<button className="login-button" onClick={login}>Sign in</button></section></main>
  return <main><header><strong>Trade Matangi Charts</strong><nav className="screen-tabs">{screens.map(screen => <button key={screen.id} className={screen.id === activeScreenId ? 'active' : ''} onClick={() => { setActiveScreenId(screen.id); setMaximizedTileId(null) }}>{screen.name}</button>)}<button className="new-screen" onClick={addScreen}>＋</button></nav>{(['Browse', 'Live', 'Replay', 'Stepwise'] as const).map(value => <button className={mode === value ? 'selected mode-button' : 'mode-button'} onClick={() => setMode(value)} key={value}>{value}</button>)}<label className="layout-control">Layout <select value={activeScreen.tiles.length} onChange={event => setTileCount(Number(event.target.value))}><option value="1">1 tile</option><option value="2">2 tiles</option><option value="4">4 tiles</option></select></label><span className={`connection ${connection}`}>● {connection}</span><button onClick={() => { if (hasNativeHost) void invoke('desktop_logout'); setBrowserToken(''); setConnection('authentication_required') }}>Log out</button></header><section className={`tile-grid tiles-${activeScreen.tiles.length} ${maximizedTileId ? 'has-maximized' : ''}`}>{activeScreen.tiles.map(tile => <DesktopTile key={tile.id} config={tile} catalogue={catalogue} connection={connection} api={api} maximized={maximizedTileId === tile.id} onConfigure={() => setPickerTileId(tile.id)} onMaximize={() => setMaximizedTileId(current => current === tile.id ? null : tile.id)} onIntervalChange={interval => saveTile({ ...tile, interval })} />)}</section>{pickerTile && <InstrumentPicker initial={pickerTile} catalogue={catalogue} api={api} onSave={saveTile} onClose={() => setPickerTileId(null)} />}</main>
}
